package quizbackend.seaBattleApi.stateMachine.statesAndEvents

enum class GameState {
    MAIN_MENU,
    ONLINE_LOBBY,
    OFFLINE_LOBBY,
    ONE_PLAYER_READY,
    BOTH_PLAYERS_READY,
    IS_ALL_ALIVE,
    IS_ALL_ONLINE,
    ONLINE_GAME_IN_PROCESS,
    ONLINE_GAME_IN_PROCESS_ATTACK_STATE,
    OFFLINE_GAME_IN_PROCESS_ATTACK_STATE,
    OFFLINE_GAME_IN_PROCESS_WITH_ONE_PLAYER_IN_WAITING_ROOM_ATTACK_STATE,
    OFFLINE_GAME_IN_PROCESS_WITH_ONE_PLAYER_IN_WAITING_ROOM,
    OFFLINE_GAME_IN_PROCESS,
    GAME_OVER,
    PLAYER_DISCONNECTED
}
